---
apiVersion: v1
kind: Service
metadata:
  name: k6
spec:
  ports:
  - name: k6
    port: 1000
    targetPort: 3000
  selector:
    app: k6
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: k6-influx
spec:
  ports:
  - name: k6-influx
    port: 1001
    targetPort: 8086
  selector:
    app: k6
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k6
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k6
    spec:
      containers:
      - name: k6
        image: k6registry.azurecr.io/k6:0.1
        env:
        - name: filek6
          value: k6.js
        ports:
        - name: http
          containerPort: 3000
        - name: http1
          containerPort: 8086
        resources:
          limits:
            memory: "512Mi"
            cpu: "400m"
        imagePullPolicy: Always
